openai:
  provider: openai
  document_metadata:
    model: gpt-4o
    temperature: 0.1
    response_format: json_object

  image_analysis_regular:
    model: gpt-4o
    temperature: 0.1
    response_format: json_object

  image_text_extraction:
    model: gpt-4o
    temperature: 0.1

  validation:
    model_type: reasoning_model
    model: o3
    response_format: json_schema
    reasoning_effort: medium