import asyncio
import json
import re 
import traceback
from pathlib import Path
from typing import List, Optional
from agents import Runner, trace
from llm.llm_engine import News_Search_Agent, WebSearchItem

def _slug(text: str, max_len: int = 60) -> str:
    """Return a filesystem-safe slug no longer than *max_len*."""
    safe = re.sub(r"[^A-Za-z0-9._-]+", "_", text) 
    return safe[:max_len] or "query"


def _save_raw_output(core_term: str, output: str,
                     out_dir: Path = Path("debug_news_prompts")) -> None:
    """Persist the raw JSON/string returned by the search agent for inspection."""
    out_dir.mkdir(exist_ok=True)
    fname = _slug(core_term) + ".txt"
    (out_dir / fname).write_text(output, encoding="utf-8")


async def run_single_search(item: WebSearchItem) -> Optional[str]:
    """Run *Agent_2_Search* for a single *WebSearchItem*.

    Parameters
    ----------
    item : WebSearchItem
        Query + freshness specification generated by the planner.

    Returns
    -------
    Optional[str]
        The raw agent output (JSON string or the fixed phrase) or *None* if an error occurred.
    """
    prompt = f"{item.query}\nFreshness: {item.freshness}"
    try:
        with trace(f"Agent 2: Executing OSINT search"):
            run = await Runner.run(News_Search_Agent, prompt)
        raw_output = run.final_output 
        _save_raw_output(item.query, raw_output)
        return raw_output
    except Exception:
        print(f"[ERROR] search failed for {item.query}")
        traceback.print_exc()
        return None


async def run_searches_concurrently(search_items: List[WebSearchItem]) -> List[str]:
    """Execute multiple searches concurrently and collect the raw outputs."""
    tasks = [asyncio.create_task(run_single_search(it)) for it in search_items]

    completed: List[str] = []
    total = len(tasks)
    done = 0
    for task in asyncio.as_completed(tasks):
        res = await task
        done += 1
        print(f"[search {done}/{total}] done")
        if res is not None:
            completed.append(res)
    return completed